// Code generated by hertz generator.

package task

import (
	"github.com/cloudwego/hertz/pkg/app"
	"hz-server/internal/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _openapiMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.Trace(),
	}
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tasksMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querytaskMw() []app.HandlerFunc {
	// your code...
	return nil
}
