// Code generated by hertz generator.

package main

import (
	"context"
	"flag"
	"log"

	"github.com/cloudwego/hertz/pkg/app/server"
	"hz-server/internal/app"
	"hz-server/internal/config"
	"hz-server/internal/database"
	"hz-server/internal/downstream"
	"hz-server/internal/logger"
	"hz-server/internal/signature"
)

func main() {
	configPath := flag.String("config", "config/app.yaml", "path to config file")
	flag.Parse()

	cfg, err := config.Init(*configPath)
	if err != nil {
		log.Fatalf("init config: %v", err)
	}

	appLogger, err := logger.New(cfg.Logger)
	if err != nil {
		log.Fatalf("init logger: %v", err)
	}

	ds, err := database.Init(context.Background(), cfg.Database)
	if err != nil {
		log.Fatalf("init database: %v", err)
	}
	defer ds.Close()

	downstreamClients, err := downstream.Init(cfg.Downstream)
	if err != nil {
		log.Fatalf("init downstream clients: %v", err)
	}

	signatureVerifier, err := signature.NewVerifier(signature.Config{
		Enabled: cfg.Signature.Enabled,
		Secret:  cfg.Signature.Secret,
		Header:  cfg.Signature.Header,
	})
	if err != nil {
		log.Fatalf("init signature verifier: %v", err)
	}

	container, err := app.NewContainer(ds, downstreamClients, appLogger, signatureVerifier)
	if err != nil {
		log.Fatalf("init container: %v", err)
	}
	app.Init(container)

	h := server.Default(server.WithHostPorts(cfg.Server.Addr))

	register(h)
	h.Spin()
}
