// Code generated by hertz generator.

package main

import (
	"context"
	"flag"
	"log"

	"github.com/cloudwego/hertz/pkg/app/server"
	"hz-server/internal/app"
	"hz-server/internal/config"
	"hz-server/internal/database"
	"hz-server/internal/downstream"
)

func main() {
	configPath := flag.String("config", "config/app.yaml", "path to config file")
	flag.Parse()

	cfg, err := config.Init(*configPath)
	if err != nil {
		log.Fatalf("init config: %v", err)
	}

	ds, err := database.Init(context.Background(), cfg)
	if err != nil {
		log.Fatalf("init database: %v", err)
	}
	defer ds.Close()

	downstreamClients, err := downstream.Init(cfg.Downstream)
	if err != nil {
		log.Fatalf("init downstream clients: %v", err)
	}

	container, err := app.NewContainer(ds, downstreamClients)
	if err != nil {
		log.Fatalf("init container: %v", err)
	}
	app.Init(container)

	h := server.Default(server.WithHostPorts(cfg.Server.Addr))

	register(h)
	h.Spin()
}
