// Code generated by hertz generator.

package subtask

import (
	"github.com/cloudwego/hertz/pkg/app"
	internalapp "hz-server/internal/app"
	"hz-server/internal/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _consoleMw() []app.HandlerFunc {
	container := internalapp.MustDefault()
	return []app.HandlerFunc{
		middleware.Signature(container.SignatureVerifier, container.Logger),
	}
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _subtasksMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsubtaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listsubtasksMw() []app.HandlerFunc {
	// your code...
	return nil
}
