// Code generated by hertz generator.

package subtask

import (
	"context"
	"errors"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	subtask "hz-server/biz/model/console/subtask"
	internalapp "hz-server/internal/app"
	subtaskdomain "hz-server/internal/subtask/domain"
)

// GetSubtask .
// @router /console/v1/subtasks/:subtask_id [GET]
func GetSubtask(ctx context.Context, c *app.RequestContext) {
	var err error
	var req subtask.GetSubtaskRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	subtaskService := internalapp.MustDefault().SubtaskService
	item, err := subtaskService.GetSubtask(ctx, req.TenantID, req.SubtaskID)
	if err != nil {
		if errors.Is(err, subtaskdomain.ErrSubtaskNotFound) {
			c.JSON(consts.StatusNotFound, &subtask.GetSubtaskResponse{Code: consts.StatusNotFound, Message: "subtask not found"})
			return
		}
		c.JSON(consts.StatusInternalServerError, &subtask.GetSubtaskResponse{Code: consts.StatusInternalServerError, Message: "internal server error"})
		return
	}

	c.JSON(consts.StatusOK, &subtask.GetSubtaskResponse{
		Code:    consts.StatusOK,
		Message: "ok",
		Data:    toConsoleSubtaskInfo(item),
	})
}

// ListSubtasks .
// @router /console/v1/subtasks [GET]
func ListSubtasks(ctx context.Context, c *app.RequestContext) {
	var err error
	var req subtask.ListSubtasksRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	subtaskService := internalapp.MustDefault().SubtaskService
	items, err := subtaskService.ListSubtasks(ctx, req.TenantID)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, &subtask.ListSubtasksResponse{
			Code:    consts.StatusInternalServerError,
			Message: "internal server error",
		})
		return
	}

	c.JSON(consts.StatusOK, &subtask.ListSubtasksResponse{
		Code:    consts.StatusOK,
		Message: "ok",
		Data:    toConsoleSubtaskInfoList(items),
	})
}
