// Code generated by hertz generator.

package subtask

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	subtask "hz-server/biz/model/console/subtask"
	"hz-server/internal/apperror"
)

// GetSubtask .
// @router /console/v1/subtasks/:subtask_id [GET]
func GetSubtask(ctx context.Context, c *app.RequestContext) {
	var err error
	var req subtask.GetSubtaskRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	item, err := service().GetSubtask(ctx, req.TenantID, req.SubtaskID)
	if err != nil {
		appErr := apperror.OrInternal(err)
		c.JSON(consts.StatusOK, &subtask.GetSubtaskResponse{Code: appErr.Code, Message: appErr.Message})
		return
	}

	c.JSON(consts.StatusOK, &subtask.GetSubtaskResponse{
		Code:    consts.StatusOK,
		Message: "ok",
		Data:    toConsoleSubtaskInfo(item),
	})
}

// ListSubtasks .
// @router /console/v1/subtasks [GET]
func ListSubtasks(ctx context.Context, c *app.RequestContext) {
	var err error
	var req subtask.ListSubtasksRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	items, err := service().ListSubtasks(ctx, toListSubtasksInput(req))
	if err != nil {
		appErr := apperror.OrInternal(err)
		c.JSON(consts.StatusOK, &subtask.ListSubtasksResponse{
			Code:    appErr.Code,
			Message: appErr.Message,
		})
		return
	}

	c.JSON(consts.StatusOK, &subtask.ListSubtasksResponse{
		Code:    consts.StatusOK,
		Message: "ok",
		Data:    toConsoleSubtaskInfoList(items),
	})
}
