// Code generated by hertz generator.

package task_runner_service

import (
	"context"
	"fmt"

	"github.com/cloudwego/hertz/pkg/common/config"
	"github.com/cloudwego/hertz/pkg/protocol"
	taskrunner "hz-server/biz/model/downstream/taskrunner"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type Client interface {
	StartTask(context context.Context, req *taskrunner.StartTaskCommand, reqOpt ...config.RequestOption) (resp *taskrunner.StartTaskResult, rawResponse *protocol.Response, err error)
}

type TaskRunnerServiceClient struct {
	client *cli
}

func NewTaskRunnerServiceClient(hostUrl string, ops ...Option) (Client, error) {
	opts := getOptions(append(ops, withHostUrl(hostUrl))...)
	cli, err := newClient(opts)
	if err != nil {
		return nil, err
	}
	return &TaskRunnerServiceClient{
		client: cli,
	}, nil
}

func (s *TaskRunnerServiceClient) StartTask(context context.Context, req *taskrunner.StartTaskCommand, reqOpt ...config.RequestOption) (resp *taskrunner.StartTaskResult, rawResponse *protocol.Response, err error) {
	httpResp := &taskrunner.StartTaskResult{}
	ret, err := s.client.r().
		setContext(context).
		setQueryParams(map[string]interface{}{}).
		setPathParams(map[string]string{}).
		addHeaders(map[string]string{}).
		setFormParams(map[string]string{}).
		setFormFileParams(map[string]string{}).
		setBodyParam(req).
		setRequestOption(reqOpt...).
		setResult(httpResp).
		execute("POST", "/tasks/start")
	if err != nil {
		return nil, nil, err
	}

	resp = httpResp
	rawResponse = ret.rawResponse
	return resp, rawResponse, nil
}

var defaultClient, _ = NewTaskRunnerServiceClient("")

func ConfigDefaultClient(ops ...Option) (err error) {
	defaultClient, err = NewTaskRunnerServiceClient("", ops...)
	return
}

func StartTask(context context.Context, req *taskrunner.StartTaskCommand, reqOpt ...config.RequestOption) (resp *taskrunner.StartTaskResult, rawResponse *protocol.Response, err error) {
	return defaultClient.StartTask(context, req, reqOpt...)
}
