// Code generated by hertz generator.

package subtask

import (
	"context"
	"errors"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	subtask "hz-server/biz/model/openapi/subtask"
	internalapp "hz-server/internal/app"
	subtaskdomain "hz-server/internal/subtask/domain"
)

// QuerySubtask .
// @router /openapi/v1/subtasks/:subtask_id [GET]
func QuerySubtask(ctx context.Context, c *app.RequestContext) {
	var err error
	var req subtask.QuerySubtaskRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	subtaskService := internalapp.MustDefault().SubtaskService
	item, err := subtaskService.GetSubtask(ctx, req.TenantID, req.SubtaskID)
	if err != nil {
		if errors.Is(err, subtaskdomain.ErrSubtaskNotFound) {
			c.JSON(consts.StatusNotFound, &subtask.QuerySubtaskResponse{Code: consts.StatusNotFound, Message: "subtask not found"})
			return
		}
		c.JSON(consts.StatusInternalServerError, &subtask.QuerySubtaskResponse{Code: consts.StatusInternalServerError, Message: "internal server error"})
		return
	}

	c.JSON(consts.StatusOK, &subtask.QuerySubtaskResponse{
		Code:    consts.StatusOK,
		Message: "ok",
		Data:    toOpenAPISubtaskInfo(item),
	})
}
