// Code generated by hertz generator.

package subtask

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	subtask "hz-server/biz/model/openapi/subtask"
	"hz-server/internal/apperror"
)

// QuerySubtask .
// @router /openapi/v1/subtasks/:subtask_id [GET]
func QuerySubtask(ctx context.Context, c *app.RequestContext) {
	var err error
	var req subtask.QuerySubtaskRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	item, err := service().GetSubtask(ctx, req.TenantID, req.SubtaskID)
	if err != nil {
		appErr := apperror.OrInternal(err)
		c.JSON(consts.StatusOK, &subtask.QuerySubtaskResponse{Code: appErr.Code, Message: appErr.Message})
		return
	}

	c.JSON(consts.StatusOK, &subtask.QuerySubtaskResponse{
		Code:    consts.StatusOK,
		Message: "ok",
		Data:    toOpenAPISubtaskInfo(item),
	})
}
