// Code generated by hertz generator.

package task

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	task "hz-server/biz/model/openapi/task"
	"hz-server/internal/apperror"
)

// QueryTask .
// @router /openapi/v1/tasks/:task_id [GET]
func QueryTask(ctx context.Context, c *app.RequestContext) {
	var err error
	var req task.QueryTaskRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	item, err := service().GetTask(ctx, req.TenantID, req.TaskID)
	if err != nil {
		appErr := apperror.OrInternal(err)
		c.JSON(consts.StatusOK, &task.QueryTaskResponse{Code: appErr.Code, Message: appErr.Message})
		return
	}

	c.JSON(consts.StatusOK, &task.QueryTaskResponse{
		Code:    consts.StatusOK,
		Message: "ok",
		Data:    toOpenAPITaskInfo(item),
	})
}
