// Code generated by hertz generator.

package task

import (
	"context"
	"errors"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	task "hz-server/biz/model/openapi/task"
	internalapp "hz-server/internal/app"
	taskdomain "hz-server/internal/task/domain"
)

// QueryTask .
// @router /openapi/v1/tasks/:task_id [GET]
func QueryTask(ctx context.Context, c *app.RequestContext) {
	var err error
	var req task.QueryTaskRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	taskService := internalapp.MustDefault().TaskService
	item, err := taskService.GetTask(ctx, req.TenantID, req.TaskID)
	if err != nil {
		if errors.Is(err, taskdomain.ErrTaskNotFound) {
			c.JSON(consts.StatusNotFound, &task.QueryTaskResponse{Code: consts.StatusNotFound, Message: "task not found"})
			return
		}
		c.JSON(consts.StatusInternalServerError, &task.QueryTaskResponse{Code: consts.StatusInternalServerError, Message: "internal server error"})
		return
	}

	c.JSON(consts.StatusOK, &task.QueryTaskResponse{
		Code:    consts.StatusOK,
		Message: "ok",
		Data:    toOpenAPITaskInfo(item),
	})
}
