// Code generated by hertz generator.

package task

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	task "hz-server/biz/model/console/task"
	"hz-server/internal/apperror"
)

// GetTask .
// @router /console/v1/tasks/:task_id [GET]
func GetTask(ctx context.Context, c *app.RequestContext) {
	var err error
	var req task.GetTaskRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	item, err := service().GetTask(ctx, req.TenantID, req.TaskID)
	if err != nil {
		appErr := apperror.OrInternal(err)
		c.JSON(consts.StatusOK, &task.GetTaskResponse{Code: appErr.Code, Message: appErr.Message})
		return
	}

	c.JSON(consts.StatusOK, &task.GetTaskResponse{
		Code:    consts.StatusOK,
		Message: "ok",
		Data:    toConsoleTaskInfo(item),
	})
}

// StartTask .
// @router /console/v1/tasks/:task_id/start [POST]
func StartTask(ctx context.Context, c *app.RequestContext) {
	var err error
	var req task.StartTaskRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	result, err := service().StartTask(ctx, toStartTaskInput(req))
	if err != nil {
		appErr := apperror.OrInternal(err)
		c.JSON(consts.StatusOK, &task.StartTaskResponse{Code: appErr.Code, Message: appErr.Message})
		return
	}

	c.JSON(consts.StatusOK, &task.StartTaskResponse{
		Code:    consts.StatusOK,
		Message: "ok",
		Data:    toStartTaskResult(result),
	})
}
