// Code generated by hertz generator.

package task

import (
	"context"
	"errors"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	task "hz-server/biz/model/console/task"
	internalapp "hz-server/internal/app"
	taskdomain "hz-server/internal/task/domain"
	taskservice "hz-server/internal/task/service"
)

// GetTask .
// @router /console/v1/tasks/:task_id [GET]
func GetTask(ctx context.Context, c *app.RequestContext) {
	var err error
	var req task.GetTaskRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	taskService := internalapp.MustDefault().TaskService
	item, err := taskService.GetTask(ctx, req.TenantID, req.TaskID)
	if err != nil {
		if errors.Is(err, taskdomain.ErrTaskNotFound) {
			c.JSON(consts.StatusNotFound, &task.GetTaskResponse{Code: consts.StatusNotFound, Message: "task not found"})
			return
		}
		c.JSON(consts.StatusInternalServerError, &task.GetTaskResponse{Code: consts.StatusInternalServerError, Message: "internal server error"})
		return
	}

	c.JSON(consts.StatusOK, &task.GetTaskResponse{
		Code:    consts.StatusOK,
		Message: "ok",
		Data:    toConsoleTaskInfo(item),
	})
}

// StartTask .
// @router /console/v1/tasks/:task_id/start [POST]
func StartTask(ctx context.Context, c *app.RequestContext) {
	var err error
	var req task.StartTaskRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	taskService := internalapp.MustDefault().TaskService
	result, err := taskService.StartTask(ctx, taskservice.StartTaskInput{
		TenantID: req.TenantID,
		TaskID:   req.TaskID,
	})
	if err != nil {
		if errors.Is(err, taskdomain.ErrTaskNotFound) {
			c.JSON(consts.StatusNotFound, &task.StartTaskResponse{Code: consts.StatusNotFound, Message: "task not found"})
			return
		}
		if errors.Is(err, taskdomain.ErrTaskNotStartable) {
			c.JSON(consts.StatusConflict, &task.StartTaskResponse{Code: consts.StatusConflict, Message: "task is not startable"})
			return
		}
		c.JSON(consts.StatusInternalServerError, &task.StartTaskResponse{Code: consts.StatusInternalServerError, Message: "internal server error"})
		return
	}

	c.JSON(consts.StatusOK, &task.StartTaskResponse{
		Code:    consts.StatusOK,
		Message: "ok",
		Data:    toStartTaskResult(result),
	})
}
