// Code generated by hertz generator.

package task

import (
	"github.com/cloudwego/hertz/pkg/app"
	internalapp "hz-server/internal/app"
	"hz-server/internal/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _consoleMw() []app.HandlerFunc {
	container := internalapp.MustDefault()
	return []app.HandlerFunc{
		middleware.Signature(container.SignatureVerifier, container.Logger),
	}
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tasksMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _task_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _starttaskMw() []app.HandlerFunc {
	// your code...
	return nil
}
