// Code generated by hertz generator.

package task

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _consoleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tasksMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettaskMw() []app.HandlerFunc {
	// your code...
	return nil
}
