// Code generated by hertz generator.

package subtask

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _openapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _subtasksMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querysubtaskMw() []app.HandlerFunc {
	// your code...
	return nil
}
