// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	console_subtask "hz-server/biz/router/console/subtask"
	console_task "hz-server/biz/router/console/task"
	openapi_subtask "hz-server/biz/router/openapi/subtask"
	openapi_task "hz-server/biz/router/openapi/task"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	openapi_subtask.Register(r)

	openapi_task.Register(r)

	console_subtask.Register(r)

	console_task.Register(r)
}
